# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

test_results_dir: &test_results_dir /tmp/test_results

jobs:
  run-tests:
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:1.16.2
        environment:
          TF_ACC_TERRAFORM_VERSION: 1.0.0
          TEST_RESULTS_DIR: *test_results_dir

    working_directory: /go/src/github.com/hashicorp/terraform-provider-tfe

    steps:
      - checkout

      - run: go get -v -t -d ./...

      - run:
          name: Make test results directory
          command: mkdir -p $TEST_RESULTS_DIR

      # Split these out from the testacc make cmd
      # because gotestsum requires only junit stdout
      - run:
          name: fmt check
          command: make fmtcheck

      - run:
          name: go vet
          command: make vet

      # This is added because `make test` is run as part of the release process
      # Most of our tests are Acceptance tests, and therefore are skipped when
      # part of this. But we want to catch future mistakes by ensuring this
      # passes.
      - run:
          name: go test
          command: make test

      - run:
          name: Run tests
          command: |
              TF_ACC=1 gotestsum --format short-verbose --junitfile \
              $TEST_RESULTS_DIR/tests.xml -- `go list ./... |grep -v 'vendor'` -v -timeout 30m
          no_output_timeout: 1800

      - store_test_results:
          path: *test_results_dir

workflows:
  version: 2
  build-and-test:
    jobs:
      - run-tests:
          context: terraform-provider-tfe build access
